import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";

const outer = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outer.className}>
      <Header />
        <div className='md:px-20'>
        
          {children}
        </div>
        <Footer/>
        </body>
    </html>
  );
}
